# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.8
_src_path: https://github.com/jupyterlab/extension-template
author_email: tim.metzler@h-brs.de
author_name: Tim Metzler
has_binder: false
has_settings: false
kind: frontend
labextension_name: '@e2xgrader/choice-cells'
project_short_description: A JupyterLab extension that provides single and multiplechoice
    cells
python_name: e2xgrader_choice_cells
repository: https://github.com/e2xgrader/e2xgrader-choice-cells
test: true

